dcns/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = (
[
    path('admin/', admin.site.urls),
            path("", include("web.urls", namespace="web")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        path(
            "OneSignalSDKWorker.js",
            TemplateView.as_view(
                template_name="OneSignalSDKWorker.js", content_type="text/javascript"
            ),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "DCNS Administration"
admin.site.site_title = "DCNS Admin Portal"
admin.site.index_title = "Welcome to DCNS Admin Portal"

web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("services/", views.ServicesView.as_view(), name="services"),
    path("service-detail/<slug:slug>/",views.ServiceDetailView.as_view(),name="service_detail"),
    path("updates/", views.UpdatesView.as_view(), name="updates"),
    path("updates-detail/<slug:slug>/",views.UpdatesDetailView.as_view(),name="updates_detail"),
    path("faq/", views.FaqView.as_view(), name="faq"),
    path("contact/", views.ContactView.as_view(), name="contact"),



]

templates/web/about.html
{% extends 'web/partials/base-two.html' %}
{% load static %}
{% block title %}
  About
{% endblock %}

{% block content %}
  <!-- Breadcrumb Start -->
  <div class="main-bg">
    <div class="container-fluid p-0">
      <div class="text-left iq-breadcrumb-one iq-bg-over black">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-sm-12">
              <nav aria-label="breadcrumb" class="text-center iq-breadcrumb-two">
                <h2 class="title">About Us</h2>
              <ol class="breadcrumb main-bg">
                  <li class="breadcrumb-item">
                    <a href="{% url 'web:index' %}"><i class="fa fa-home mr-2"></i>Home</a>
                  </li>
                  <li class="breadcrumb-item active">About Us</li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Breadcrumb End -->

  <!-- Counter Start -->
  <section class="iq-counter-section iq-pb-70">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-lg-0 mb-5">
          <div class="iq-title-box iq-title-default iq-title-box-2">
            <div class="iq-title-icon"></div>
            <span class="iq-subtitle">About Us</span>
            <h2 class="iq-title">We lead and support our customer’s cloud</h2>
            <p class="iq-title-desc">It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout.</p>
          </div>
          <div class="iq-list iq-two-column">
            <ul class="iq-list-with-icon">
              <li>
                <i class="ion ion-checkmark-round"></i>Boost SEO ranking
              </li>
              <li>
                <i class="ion ion-checkmark-round"></i> Social Sharing
              </li>
              <li>
                <i class="ion ion-checkmark-round"></i>Marketing
              </li>
              <li>
                <i class="ion ion-checkmark-round"></i>Retention
              </li>
              <li>
                <i class="ion ion-checkmark-round"></i> Visual Reviews
              </li>
              <li>
                <i class="ion ion-checkmark-round"></i>
                Reviews Generation
              </li>
            </ul>
          </div>
          <div class="iq-btn-container mt-4">
            <a class="iq-button iq-btn-medium iq-btn-round iq-btn-flat d-inline" href="javascript:void(0)">Read More</a>
          </div>
        </div>
        <div class="col-lg-6">
          <div class="row">
            <div class="col-lg-6 col-md-6">
              <div class="iq-counter text-center iq-box-shadow iq-counter-style-1">
                <div class="counter-content">
                  <p class="iq-counter-info">
                    <span class="timer" data-to="50" data-speed="5000">50</span>
                    <span class="counter-after-content"></span>
                    <span class="counter-symbol">+</span>
                  </p>
                  <h5 class="counter-title-text">Engineers and Developers</h5>
                </div>
              </div>
              <div class="iq-counter text-center iq-box-shadow iq-counter-style-1">
                <div class="counter-content">
                  <p class="iq-counter-info">
                    <span class="timer" data-to="100" data-speed="5000">100</span>
                    <span class="counter-after-content">k</span>
                    <span class="counter-symbol">+</span>
                  </p>
                  <h5 class="counter-title-text">Customers</h5>
                </div>
              </div>
            </div>
            <div class="col-lg-6 col-md-6">
              <div class="iq-counter text-center iq-box-shadow iq-counter-style-1">
                <div class="counter-content">
                  <p class="iq-counter-info">
                    <span class="timer" data-to="35" data-speed="5000">35</span>
                    <span class="counter-after-content">m</span>
                    <span class="counter-symbol">+</span>
                  </p>
                  <h5 class="counter-title-text">Instances Deployed</h5>
                </div>
              </div>
              <div class="iq-counter text-center iq-box-shadow iq-counter-style-1">
                <div class="counter-content">
                  <p class="iq-counter-info">
                    <span class="timer" data-to="15" data-speed="5000">15</span>
                    <span class="counter-after-content">m</span>
                    <span class="counter-symbol">+</span>
                  </p>
                  <h5 class="counter-title-text">Support answers per month</h5>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Counter End -->

  <div class="misson">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-sm-12">
          <img src="{% static 'web/images/others/05.png' %}" class="img-fluid" alt="qloud" />
        </div>
        <div class="col-lg-6 col-sm-12 mb-lg-0 mb-5">
          <div class="text-left iq-title-box iq-title-default iq-title-box-2">
            <div class="iq-title-icon"></div>
            <h2 class="iq-title">Our Mission</h2>

            <p class="iq-title-desc">
              Speed ​​is key in the business world. DCNS is dedicated to enabling employees to connect with the right people,
              get the right information, and at the right time. We coexist seamlessly with technology, leveraging its potential as
               an essential business tool to achieve today’s business goals.
            </p>
          </div>
        </div>
        
      </div>
    </div>
  </div>

  <div class="misson">

    <div class="container">
      <div class="row">
        <div class="col-lg-6 col-sm-12 mb-lg-0 mb-5">
          <div class="text-left iq-title-box iq-title-default iq-title-box-2">
            <div class="iq-title-icon"></div>
            <h2 class="iq-title">Our Vision</h2>

            <p class="iq-title-desc">
              As an integrated professional community, we see an evolving landscape in which professional roles are diverse 
              and geographically diverse. In this era of activity diversity and widespread dispersion, unity becomes more 
              difficult and vital. At DCNS, we intend to overcome these challenges by leveraging our collective expertise 
              and state-of-the-art technology to create a seamless collaboration for our clients to succeed.
            </p>
          </div>
        </div>
        <div class="col-lg-6 col-sm-12">
          <img src="{% static 'web/images/others/05.png' %}" class="img-fluid" alt="qloud" />
        </div>
      </div>
    </div>
  </div>

  <!-- Counter Start -->
  <section class="main-bg main-bg-index" style="background: url('{% static 'web/images/others/06.jpg' %}') no-repeat 0 0; background-attachment: fixed; background-size:cover; ">
    <div class="container">
      <div class="row">
        <div class="col-lg-6 mb-lg-0 mb-5">
          <div class="iq-title-box iq-title-default iq-title-box-2">
            <span class="iq-subtitle ">Why choose DCNS?</span>
            <h2 class="iq-title text-white">The Choice for Innovation and Excellence</h2>
            <p class="iq-title-desc text-white">Take DCNS, where innovation meets commitment, to the forefront of your business. Customized solutions, proven success, and an unwavering customer focus make us your ideal partner for a safe and streamlined journey into the digital future. Choose DCNS and thrive with technical excellence.</p>
          </div>
          <div class="iq-list iq-two-column">
            <ul class="iq-list-with-icon">
              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                New features at Core
              </li>

              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                Solutions designed for your success
              </li>

              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                Dedicated to unparalleled service
              </li>

              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                Full track record
              </li>

              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                Approach to User-Based Communications
              </li>

              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                Security and compliance guarantee
              </li>

              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                Customer focus
              </li>

              <li class="text-white">
                <i class="ion ion-checkmark-round"></i>
                Ongoing learning and change
              </li>
            </ul>
          </div>
          <div class="iq-btn-container mt-4">
            <a class="iq-button iq-btn-medium iq-btn-round iq-btn-flat d-none" href="javascript:void(0)">Read More</a>
          </div>
        </div>
        
      </div>
    </div>
  </section>
  <!-- Counter End -->

  <!-- Icon-box Start -->
  <section class="iq-pricing-section pt-5 iq-pb-70">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="text-center iq-title-box iq-title-default iq-title-box-2">
                    <div class="iq-title-icon">
                    </div>
                    <span class="iq-subtitle">Faq</span>
                    <h2 class="iq-title">Frequently Asked Questions</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="iq-accordion  iq-accordion-semi-round iq-accordion-classic">
                    {% for faq_item in faq %}
                        <div class="iq-accordion-block">
                            <div class="iq-accordion-title">
                                <div class="iq-icon-right">
                                    <i aria-hidden="true" class="ion ion-minus-round active"></i>
                                    <i aria-hidden="true" class="ion ion-plus inactive"></i>
                                </div>
                                <h5 class="mb-0 accordion-title">{{ faq_item.title }}</h5>
                            </div>
                            <div class="iq-accordion-details">
                                <p class="iq-content-text">{{ faq_item.description|safe }}</p>
                            </div>
                        </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
  </section>
  <!-- Icon-box End -->

  <!-- back-to-top -->
  <div id="back-to-top">
    <a class="top" id="top" href="#top"><i class="ion-ios-arrow-up"></i></a>
  </div>
  <!-- back-to-top End -->
{% endblock %}

templates/web/contact.html
{% extends "web/partials/base-two.html" %}
 {% block title %}Contact{% endblock  %}
 {% load static %}

  {% block content %}

    <!-- Main-Content Start -->
    <div class="main-content">
        <!-- Breadcrumb Start -->
        <div class=" main-bg">
            <div class="container-fluid p-0">
                <div class="text-left iq-breadcrumb-one
                  iq-bg-over black     ">
                    <div class="container">
                        <div class="row align-items-center">
                            <div class="col-sm-12">
                                <nav aria-label="breadcrumb" class="text-center iq-breadcrumb-two">
                                    <h2 class="title">Contact Us</h2>
                                    <ol class="breadcrumb main-bg">
                                        <li class="breadcrumb-item"><a href="{% url "web:index" %}"><i class="fa fa-home mr-2"></i>Home</a></li>
                                        <li class="breadcrumb-item active">Contact Us</li>
                                    </ol>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Breadcrumb End -->
        <!-- Contact Start -->
        <div class=" overview-block-ptb overview-block-ptb-form">
            <div class="container">
                <div class="row">
                    <div class="col-lg-6 col-md-12">
                        <img src="{% static 'web/images/others/01.png' %}" class="img-fluid" alt="contact" />
                    </div>
                    <div class="col-lg-6 col-md-12">
                        <div class=" text-left iq-title-box iq-title-default iq-title-box-2">
                            <div class="iq-title-icon">
                            </div>
                            <span class="iq-subtitle">Get In Touch</span>
                            <h2 class="iq-title">
                        Contact With US   </h2>

                            <p class="iq-title-desc">It is a long established fact that a reader will be distracted</p>
                        </div>
                        <div role="form" class="wpcf7" id="wpcf7-f790-p785-o1" lang="en-US" dir="ltr">
                            <div class="screen-reader-response"></div>
                            <form class="row wpcf7-form ajax reload" method="post">
                                {% csrf_token %}
                                <div style="display: none;">
                                    <input type="hidden" name="_wpcf7" value="790" />
                                    <input type="hidden" name="_wpcf7_version" value="5.1.6" />
                                    <input type="hidden" name="_wpcf7_locale" value="en_US" />
                                    <input type="hidden" name="_wpcf7_unit_tag" value="wpcf7-f790-p785-o1" />
                                    <input type="hidden" name="_wpcf7_container_post" value="785" />
                                </div>
                                <div class=row>
                                    <div class="col-lg-6">
                                        <span class="wpcf7-form-control-wrap first-name">
                                            <input type="text" 
                                            name="first_name"
                                            id="first_name" 
                                            value="" size="40" 
                                            class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" 
                                            aria-required="true" aria-invalid="false" placeholder="First Name" required />
                                        </span>
                                    </div>
                                    <div class="col-lg-6">
                                        <span class="wpcf7-form-control-wrap last-name">
                                            <input type="text" 
                                            name="last_name"
                                            id="last_name" 
                                            value="" size="40" 
                                            class="wpcf7-form-control wpcf7-text wpcf7-validates-as-required" 
                                            aria-required="true" aria-invalid="false" placeholder="Last Name" required />
                                        </span>
                                    </div>
                                    <div class="col-lg-6">
                                        <span class="wpcf7-form-control-wrap your-email">
                                            <input type="email"
                                            name="email"
                                            id="email" 
                                            value="" size="40" 
                                            class="wpcf7-form-control wpcf7-text wpcf7-email wpcf7-validates-as-required wpcf7-validates-as-email"
                                            aria-required="true" aria-invalid="false" placeholder="Email Address" required />
                                        </span>
                                    </div>
                                    <div class="col-lg-6">
                                        <span class="wpcf7-form-control-wrap tel-554">
                                            <input type="tel" 
                                            name="phone" 
                                            id="phone"
                                            value=""
                                            size="40" 
                                            class="wpcf7-form-control wpcf7-text wpcf7-tel wpcf7-validates-as-tel" 
                                            aria-invalid="false" placeholder="Phone" required/>
                                        </span>
                                    </div>
                                    <div class="col-lg-12">
                                        <p> 
                                        <span class="wpcf7-form-control-wrap your-message">
                                            <textarea 
                                            name="message"
                                            id="message" 
                                            cols="40" rows="10" 
                                            class="wpcf7-form-control wpcf7-textarea" 
                                            aria-invalid="false" placeholder="Message" required></textarea>
                                        </span>
                                        </p>
                                    </div>
                                    <div class="col-lg-12">
                                        <input type="submit" value="Send" class="wpcf7-form-control wpcf7-submit" />
                                    </div>
                                </div>
                                <div class="wpcf7-response-output wpcf7-display-none"></div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>

        </div>

    </div>
    <!-- Contact End -->

    <section class="light-gray-bg">
        <div class="container">
            <div class="row">
                <div class="col-lg-4  col-md-6">
                    <div class="iq-process iq-process-step-style-2 text-center">

                        <div class="iq-process-step">

                            <div class="iq-step-content">
                                <i aria-hidden="true" class="ion ion-ios-location"></i> </div>
                            <div class="iq-step-text-area">

                                <h4 class="iq-step-title">Location</h4>

                                <span class="iq-step-desc">Abu Dhabi, UAE</span>

                            </div>

                        </div>

                    </div>
                </div>
                <div class="col-lg-4  col-md-6">
                    <div class="iq-process iq-process-step-style-2 text-center">

                        <div class="iq-process-step">

                            <div class="iq-step-content">
                                <i aria-hidden="true" class="ion ion-ios-email"></i> </div>
                            <div class="iq-step-text-area">

                                <h4 class="iq-step-title">Email</h4>

                                <span class="iq-step-desc">info@dcns.ae </span>

                            </div>

                        </div>

                    </div>
                </div>
                <div class="col-lg-4  col-md-6">
                    <div class="iq-process iq-process-step-style-2 text-center">

                        <div class="iq-process-step">

                            <div class="iq-step-content">
                                <i aria-hidden="true" class="ion ion-ios-telephone"></i> </div>
                            <div class="iq-step-text-area">

                                <h4 class="iq-step-title">Phone</h4>

                                <span class="iq-step-desc">050 742 4152</span>

                            </div>

                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- back-to-top -->
    <div id="back-to-top">
        <a class="top" id="top" href="#top"> <i class="ion-ios-arrow-up"></i> </a>
    </div>
    <!-- back-to-top End -->

    {% endblock %}

    {% block js %}
    {% include 'web/include/form-ajax.html' %}
    {% endblock %}

templates/web/updates-details.html
{% extends 'web/partials/base-two.html' %}
{% block title %}
  Contact
{% endblock %}
{% load static %}

{% block content %}
  <!-- Breadcrumb Start -->
  <div class="main-bg">
    <div class="container-fluid p-0">
      <div class="text-left iq-breadcrumb-one iq-bg-over black">
        <div class="container">
          <div class="row align-items-center">
            <div class="col-sm-12">
              <nav aria-label="breadcrumb" class="text-center iq-breadcrumb-two">
                <h2 class="title">Update Details</h2>
                <ol class="breadcrumb main-bg">
                  <li class="breadcrumb-item">
                    <a href="{% url 'web:index' %}"><i class="fa fa-home mr-2"></i>Home</a>
                  </li>
                  <li class="breadcrumb-item active">Update Details</li>
                </ol>
              </nav>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- Breadcrumb End -->
  <!-- Blog Start -->
  <div class="iq-blog-section overview-block-ptb">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-sm-12 mt-lg-0 mt-5">
          <article id="post-218" class="post-218 post type-post status-publish format-standard has-post-thumbnail hentry category-marketing tag-business tag-marketing">
            <div class="iq-blog-box">
              <div class="iq-blog-image clearfix">
                <img src="{{ updates.image.url }}" class="img-fluid" alt="qloud" />
                <ul class="iq-blogtag">
                  <li>
                    <a href="javascript:void(0)">{{updates.category}}</a>
                  </li>
                </ul>
              </div>
              <div class="iq-blog-detail">
                <div class="iq-blog-meta">
                  <ul class="iq-postdate">
                    <li class="list-inline-item">
                      <i class="fa fa-calendar mr-2"></i>
                      <span class="screen-reader-text">Posted on</span> 
                      <a href="javascript:void(0)" rel="bookmark">
                        <time class="entry-date published updated" datetime="2020-02-17T06:44:40+00:00">{{ updates.pub_date}}</time>
                     </a>
                    </li>
                  </ul>
                  <h3>{{updates.title}}</h3>
                </div>
                
                <div class="blog-content">
                  <p>{{updates.content}}</p>
                </div>
              </div>
            </div>
          </article>
          <!-- #post-## -->
        </div>

        <div class="col-lg-4 col-sm-12 mt-lg-0 mt-5">
          <aside id="secondary" class="widget-area" aria-label="Blog Sidebar">
            <div id="recent-posts-2" class="widget widget_recent_entries">
              <h2 class="widget-title">Recent Posts</h2>
              <ul>
                {% for recent_post in recent_posts %}
                <li>
                  <a href="{% url 'web:updates_detail' slug=recent_post.slug %}">{{ recent_post.title }}</a>
                </li>
                {% endfor %}
              </ul>
            </div>
          </aside>
          <!-- #secondary -->
        </div>
      </div>
      <!-- #row -->
    </div>
  </div>
{% endblock %}
{% block js %}
  {% include 'web/include/form-ajax.html' %}
{% endblock %}