dcns/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = (
[
    path('admin/', admin.site.urls),
            path("", include("web.urls", namespace="web")),
        path(
            "sitemap.xml",
            TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml"),
        ),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="robots.txt", content_type="text/plain"),
        ),
        path(
            "OneSignalSDKWorker.js",
            TemplateView.as_view(
                template_name="OneSignalSDKWorker.js", content_type="text/javascript"
            ),
        ),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

admin.site.site_header = "DCNS Administration"
admin.site.site_title = "DCNS Admin Portal"
admin.site.index_title = "Welcome to DCNS Admin Portal"

web/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = "web"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("services/", views.ServicesView.as_view(), name="services"),
    path("service-detail/<slug:slug>/",views.ServiceDetailView.as_view(),name="service_detail"),
    path("updates/", views.UpdatesView.as_view(), name="updates"),
    path("updates-detail/<slug:slug>/",views.UpdatesDetailView.as_view(),name="updates_detail"),
    path("faq/", views.FaqView.as_view(), name="faq"),
    path("contact/", views.ContactView.as_view(), name="contact"),



]

templates/web/partials/include/navbar-white.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url "web:index" %}"><img class="img-fluid" src="{% static 'web/images/dcns logo.svg' %}" alt="img" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="menu-btn d-inline-block" id="menu-btn">
        <span class="line"></span>
        <span class="line"></span>
        <span class="line"></span>
      </span>
      <span class="ion-navicon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto w-100 justify-content-end">
        <li class="nav-item ">
          <a class="nav-link {% if is_index %}active{% endif %}" href="{% url "web:index" %}">Home</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link {% if is_about %}active{% endif %}" href="{% url "web:about" %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if is_service %}active{% endif %}" href="{% url "web:services" %}">Services</a>
        </li>

        <li class="nav-item">
          <a class="nav-link {% if is_updates %}active{% endif %}" href="{% url "web:updates" %}">Updates</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link {% if is_contact %}active{% endif %}" href="{% url "web:contact" %}">Contacts</a>
        </li>
      </ul>
    </div>
    <div class="sub-main d-none">
      <ul>
        <li class="d-inline">
          <a href="javascript:void(0)" class="login iq-button iq-btn-outline iq-btn-round" target="_blank">Login</a>
        </li>
        <li class="d-inline">
          <a href="javascript:void(0)" class="signup iq-button default iq-btn-round" target="_blank">Sign Up</a>
        </li>
      </ul>
    </div>
  </nav>

templates/web/partials/include/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand" href="{% url 'web:index' %}"><img class="img-fluid" src="{% static 'web/images/dcns logo.svg' %}" alt="img" /></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="menu-btn d-inline-block" id="menu-btn">
        <span class="line"></span>
        <span class="line"></span>
        <span class="line"></span>
      </span>
      <span class="ion-navicon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto w-100 justify-content-end">
        <li class="nav-item ">
          <a class="nav-link {% if is_index %}active{% endif %}" href="{% url "web:index" %}">Home</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link {% if is_about %}active{% endif %}" href="{% url "web:about" %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link {% if is_service %}active{% endif %}" href="{% url "web:services" %}">Services</a>
        </li>

        <li class="nav-item">
          <a class="nav-link {% if is_updates %}active{% endif %}" href="{% url "web:updates" %}">Updates</a>
        </li>
        <li class="nav-item ">
          <a class="nav-link {% if is_contact %}active{% endif %}" href="{% url "web:contact" %}">Contacts</a>
        </li>
      </ul>
    </div>
    <div class="sub-main d-none">
      <ul>
        <li class="d-inline">
          <a href="javascript:void(0)" class="login iq-button iq-btn-outline iq-btn-round" target="_blank">Login</a>
        </li>
        <li class="d-inline">
          <a href="javascript:void(0)" class="signup iq-button default iq-btn-round" target="_blank">Sign Up</a>
        </li>
      </ul>
    </div>
  </nav>